// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertUploadedVideoToGif(arg1, arg2) {
  return window['go']['main']['App']['ConvertUploadedVideoToGif'](arg1, arg2);
}

export function ConvertVideoToGif(arg1, arg2) {
  return window['go']['main']['App']['ConvertVideoToGif'](arg1, arg2);
}

export function GetFFmpegInfo() {
  return window['go']['main']['App']['GetFFmpegInfo']();
}

export function GetOutputDir() {
  return window['go']['main']['App']['GetOutputDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenOutputDir() {
  return window['go']['main']['App']['OpenOutputDir']();
}

export function SaveUploadedFile(arg1, arg2) {
  return window['go']['main']['App']['SaveUploadedFile'](arg1, arg2);
}
