// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertUploadedVideoToGif(arg1:Array<number>,arg2:string):Promise<string>;

export function ConvertVideoToGif(arg1:string,arg2:main.GifConvertOptions):Promise<string>;

export function GetFFmpegInfo():Promise<string>;

export function GetOutputDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenOutputDir():Promise<void>;

export function SaveUploadedFile(arg1:Array<number>,arg2:string):Promise<string>;
